### ISSUE TITLE
Font glyph of FNC1 has unnecessary space on left side

### ISSUE THREAD

**Issue by MugeSo** [Holger-Will/code-128-encoder#2]
Left side space must be removed because FUNC1 should be able to be placed middle of code.

**Comment by Holger-Will** [comment]
What makes you think this is the case? FUNC1 seems to work properly here... do you have an example code that does not work?

**Comment by jpgoyne** [comment]
I encountered the same issue with the extra space on the left side of the FNC 1 symbol. For example, if you encode the value **32212565** it will result in **Ò@59aÏÓ**
The calculated check symbol in this example happens to be the FNC 1 symbol. The result of the extra space breaks the barcode. Here is an image of the barcode:
![barcode](https://user-images.githubusercontent.com/6176348/31365332-4e3f07b0-ad1f-11e7-8bd9-f0229f181445.png)

Awesome project by the way!

**Comment by FrankPetrilli** [comment]
@jpgoyne, I came across this issue in production as well and spent a good while resolving and verifying its behavior.

I've uploaded a modified version of the code128.ttf [here](https://frank.petril.li/public/C128/code128.ttf) which has resolved the issue for me.

**Comment by Holger-Will** [comment]
fixed
