### ISSUE TITLE
When rendering a code in the browser, is there a minimum recommended font size?

### ISSUE THREAD

**Issue by jonsagara** [Holger-Will/code-128-encoder#6]
I see that you use 50px in your examples. Is that the minimum size we should use?

**Comment by Holger-Will** [comment]
50px is the size for `code128_XL.ttf` to produce 1px wide bars. there are other fonts as well with different height to width ratios: https://github.com/Holger-Will/code-128-encoder/tree/master/fonts

**Comment by jonsagara** [comment]
Perfect. Thanks!
